name: Workflow for Scripts

on: push

jobs: 
    script_job: 
          runs-on: ubuntu-latest #This is the RUNNER
          steps:
              - name: Checkout # This is step title 
                uses: actions/checkout@v4.2.2 # Took from Marketplace

              - name: List repo files
                run: echo "Executing a Script, homie"

              - name: Executing Shell Script
                run: |
                    chmod +x script.sh 
                    ./script.sh