name: My First Workflow

on: push

jobs: 
    first_job: 
          runs-on: ubuntu-latest
          steps:
              - name: Welcome message
                run: echo "My first GitActions"

              - name: list files
                run: list
              
              - name: Read files
                run: cat README.md