name: This lives only once
on: push

jobs:
    parallel_job:
            runs-on: ubuntu-latest
            steps:
            - name: Checkout # This is step title 
              uses: actions/checkout@v4.2.2 

            - name: Welcome message 
              run: | # Use Pipe Operator to run multiple commands under a single step
                  echo "My first GitActions"
                  ls
                  cat README.md